micronaut:
  application:
    name: exampleProject

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://10.0.0.200:5432/micronaut`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:123456}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
jpa:
  default:
    packages-to-scan:
      - 'com.conductor.example.exampleproject.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true